version: '3.1'
services:
  odoo:
    image: odoo:14.0
    ports:
      - "8001:8069"
    container_name: "odoolatihan"
    volumes:
      - ./conf:/etc/odoo
      - ./addons:/mnt/extra-addons
    
    networks:
      - dockernet

networks:
  dockernet:
    name: dockernet
    external: true